### ISSUE TITLE
[MPH-142] mvn 3.0.5 starts using maven-help-plugin 3.0 resulting in java 6 problems

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-help-plugin#255]
**[Ivan Belis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ivanbelis)** opened **[MPH-142](https://issues.apache.org/jira/browse/MPH-142?redirect=false)** and commented

We are using maven 3.0.5 with a JDK 1.6.

We did not change anything in our projects poms, but suddenly builds started failing (multiple builds).

This version of maven started using the 3.0.0 version of the help-plugin, resulting in failing builds because the 3.0.0 does not support java 6.

 

REMARK: this is not a problem of the maven-help-plugin but rather a problem with how maven determines the versions of plugins !

 

This is the error we are getting:

WARNING: Error injecting: org.apache.maven.plugins.help.ActiveProfilesMojo
java.lang.TypeNotPresentException: Type org.apache.maven.plugins.help.ActiveProfilesMojo not present
        at org.sonatype.guice.bean.reflect.URLClassSpace.loadClass(URLClassSpace.java:109)
        at org.sonatype.guice.bean.reflect.NamedClass.load(NamedClass.java:45)

Caused by: java.lang.UnsupportedClassVersionError: org/apache/maven/plugins/help/ActiveProfilesMojo : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)

 

[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-help-plugin:3.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = [file:/c:/devenv/java/.m2/repository/org/apache/maven/plugins/maven-help-plugin/3.0.0/maven-help-plugin-3.0.0.jar|file:///c:/devenv/java/.m2/repository/org/apache/maven/plugins/maven-help-plugin/3.0.0/maven-help-plugin-3.0.0.jar]

 

---

**Affects:** 3.0.0

**Attachments:**
- [image-2018-03-23-09-11-10-237.png](https://issues.apache.org/jira/secure/attachment/12915838/image-2018-03-23-09-11-10-237.png) (_6.35 kB_)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

This means simply you have not pinned your plugin version correctly but you seemed to be using maven-help-plugin somehow ?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)' analysis is correct. Fix our POM and then upgrade Java.

**Comment by jira-importer** [comment]
**[Ivan Belis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ivanbelis)** commented

Using the correct versioned plugins is indeed the best way to avoid this kind problems.   However it is a common practice to use help:active-profiles without specifying a version.

In our case we are using the help:active-profiles in all our maven Jenkins jobs.  

As a workaround we removed all the 'help:active-profiles' out of the jobs, it was only for informational purposes .

 

 

You may close the issue, i just wanted to signal the problem, because i suppose we are not the only one hitting this kind of problems with maven.
