### ISSUE TITLE
[MPH-143] The maven-help-plugin generates null pointer for multi-module project

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-help-plugin#269]
**[Damien](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dbrossar)** opened **[MPH-143](https://issues.apache.org/jira/browse/MPH-143?redirect=false)** and commented

The maven-help-plugin in version 3.0.0 generates a null pointer exception for multi-module projects when the parameter "output" is set.

The following command failed

`mvn help:effective-pom -Doutput=myoutput.xml`

with the error

`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time: 2.187 s`
`[INFO] Finished at: 2018-03-20T14:52:19+01:00`
`[INFO] Final Memory: 24M/403M`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-help-plugin:3.0.0:effective-pom (default-cli) on project OFRPDVC001: Execution default-cli of goal org.apache.maven.plugins:maven-help-plugin:3.0.0:effective-pom failed. NullPointerException -> [Help 1]`
`[ERROR]`
`[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.`
`[ERROR] Re-run Maven using the -X switch to enable full debug logging.`
`[ERROR]`
`[ERROR] For more information about the errors and possible solutions, please read the following articles:`
`[ERROR] [Help 1] [http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException](https://www.google.com/url?q=http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException&sa=D&source=hangouts&ust=1521640353977000&usg=AFQjCNFFrjILs-lEz58QZue8xxeHq7gScQ)`

It doesn't happen with the previous versions, the following command helps to prove it :

`mvn org.apache.maven.plugins:maven-help-plugin:2.2:effective-pom -Doutput=myoutput.xml`

 

---

**Affects:** 3.0.0

**Issue Links:**
- [MPH-135](https://issues.apache.org/jira/browse/MPH-135) help:effective-pom crashes with NPE in multi module builds with -Doutput set
 (_**"duplicates"**_)

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Ali Cheaito](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cheaito)** commented

We're having this issue as well. I noticed that the problem goes away if the output param is omitted, which could explain why the issue was not found in testing. 

Enabling debug reveals the source of the exception:

`Caused by: java.lang.NullPointerException`
`at org.codehaus.plexus.util.xml.XmlStreamWriter.close(XmlStreamWriter.java:75)`
`at org.codehaus.plexus.util.IOUtil.close(IOUtil.java:796)`
`at org.apache.maven.plugins.help.AbstractEffectiveMojo.writeXmlFile(AbstractEffectiveMojo.java:96)`

Looking at the AbstractEffectiveMojo code (line 96 in 3.0.0,), they use IOUtils.close(out) in the finally clause after nullifying out in the try clause. They probably meant to use closeQuietly which accounts for null references.
